### ISSUE TITLE
generate more than 1 Server-Timing header

### ISSUE THREAD

**Issue by DanielRuf** [Kanti/server-timing#46]
It would be good to have it configurable, if one (big) or multiple (short) headers should be created.

https://github.com/Kanti/server-timing/blob/main/Classes/Utility/TimingUtility.php#L166

**Comment by Kanti** [comment]
Hi @DanielRuf , can you explain to me why it is helpful to split it into multiple headers?

**Comment by DanielRuf** [comment]
Generally speaking if a header exceeds a specific length, it could lead to problems.

See also https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/431

> or when a single header field is too large

Depending on the specific server and its configuration, long header values might lead to some issues. Splitting into multiple headers can sometimes help to reduce this.

https://github.com/tuupola/server-timing-middleware/issues/25 is about the same.

**Comment by Kanti** [comment]
I did some tests, LimitRequestFieldSize dose not efect the response header sizes.

On apache the limit for a single header line seams to be 8000 characters.
On nginx it seams to be 8000 characters for all header data.
So spliting the header into multiple headers only helps if you use apache.
On apache it seams that the complete header data is not limited at all: So maybe we simply should always split it into 8190 character chunks (including the header name and the `:`)

**Comment by Kanti** [comment]
done with 1.11.0
